sudo: required

services: docker

env:
  matrix:
    - LOCO_VERSION=v4.0.x-20190929 WAGON_VERSION=v4.0.x-20190929

before_install:
  - sudo pip install docker-compose
  - ./travis/install

script:
  - docker build --no-cache -t current-latest --build-arg version=$LOCO_VERSION demo

after_success:
- ./travis/publish
