#!/bin/bash
set -ex

echo 'Setup locomotive'
cd locomotive
echo 'Launch script to create the default admin user'
docker-compose run --service-port locomotive gosu loco rake demo:setup

echo 'Run locomotive in background'
docker-compose up -d

echo 'Setup Wagon'
cd ../wagon

echo 'Download last template version'
git clone -b master https://github.com/shopinvader/shopinvader-template template

echo 'Deploy site using wagon'
sed -i 's/locomotive.localhost/locomotive:3000/g' template/config/deploy.yml
echo 'yes' | docker-compose run wagon -- gosu ubuntu bundle exec wagon deploy test -d -v

echo 'Backup mongo database'
cd ../locomotive
docker-compose down
chmod 777 data
docker-compose run locomotive -- gosu loco mongodump -h db --db shopinvader -o data

echo 'Move data to demo image'
cp -r data/* ../demo/data/
cp -r public/* ../demo/public/
