#!/bin/bash
set -e

echo 'Deploy the image on quay.io if needed'
IMAGE=quay.io/shopinvader/locomotive-shopinvader-demo

if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
  echo "Log to quay.io"
  docker login quay.io --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
  if [ "$TRAVIS_BRANCH" == "master" ]; then
    VERSION="V4.0.x"
    echo "Publish latest"
    docker tag current-latest $IMAGE:$VERSION-latest
    docker push $IMAGE:$VERSION-latest
    TAG=$VERSION-`date +%Y%m%d-%H%m`
    echo "Publish tagged $TAG"
    docker tag current-latest $IMAGE:$TAG
    docker push $IMAGE:$TAG
  else
    echo "Not pushing any image"
  fi
fi
